version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
    
sphinx:
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .

formats:
  - pdf
  - epub

jobs:
  pre_install:
    - git update-index --assume-unchanged environment.yml docs/conf.py
