site_name: P1 HPC Computing Documentation
docs_dir: docs
site_dir: site
repo_url: https://github.com/Pioneer-Centre-for-AI/private-documentation

theme:
  language: en
  name: material
  favicon: figures/logo.png
  logo: figures/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox

extra:
  social:
    - icon: material/email
      link: mailto:aicentre@ku.dk
    - icon: material/web
      link: https://www.aicentre.dk/
    - icon: fontawesome/brands/github
      link: https://github.com/Pioneer-Centre-for-AI

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/shortcuts.js

nav:
  - Home: index.md
  - About Compute Resources:
      - about.md
      - P1 DTU HPC: 01_p1_dtu_hpc.md
      - P1 NGC HPC: 02_p1_ngc_hpc.md
      - P1 Gefion HPC: 03_p1_gefion_hpc.md
  - Learning Resources: 04_learning_resources.md
  - Contribute: 05_contribute.md
