site_name: P1 Documentation
docs_dir: docs
site_dir: site
repo_url: https://github.com/Pioneer-Centre-for-AI/private-documentation

theme:
  language: en
  name: material
  favicon: figures/logo.png
  logo: figures/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox

extra:
  social:
    - icon: material/email
      link: mailto:aicentre@ku.dk
    - icon: material/web
      link: https://www.aicentre.dk/
    - icon: fontawesome/brands/github
      link: https://github.com/Pioneer-Centre-for-AI

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Get started: getstarted.md
  - Compute Resources: compute_resources.md
  - Learning Resources: learning_resources.md
  - Support: support.md
  - Contribute: contribute.md

