[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Private Documentation"
authors = [{name = "Pioneer Centre for Artifical Intelligence", email = "pioneercentreforai@gmail.com"}]
dynamic = ["version", "description"]
